### ISSUE TITLE
Re-arrange content to enhance reading and searching user experience

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#16]
💬 Emoji legends:
* 🚧 Todo.
* ✅ Done.

# ✅ Point A

:triangular_ruler: Centralize all code snippets in the dedicated tab.

📦 Done in commit [0de486d](https://github.com/righettod/www-project-secure-headers/commit/0de486dae6515e339e744f77fc351de78c5e2937)

# ✅ Point B

:triangular_ruler: Tab **Technical Resources**:

* Use a table to display the information.
* Update script to check for dead project.

📦 Done in commit [64cd78b](https://github.com/OWASP/www-project-secure-headers/commit/64cd78b6d0bc68c731f67955f1a918a43bd25b31)

# ✅ Point C

Fix the table size via CSS

![image](https://user-images.githubusercontent.com/1573775/224084579-eb1d4dda-105b-4fda-8a50-a904c4f7491a.png)

Doc: https://www.w3docs.com/snippets/css/how-to-set-the-width-of-the-table-column.html

📦 Done in commit [aee0c7](https://github.com/OWASP/www-project-secure-headers/commit/7dc2af6567e7750a66a11b09098c1ccb17aee0c7

# ✅ Point D

:triangular_ruler: Modify tab order like this :

0. Main
1. Response Headers
2. Browser Support (and sync the tab name)
3. Best Practices
4. Technical Resources
5. Code Snippets
6. Miscellaneous
7. Top Websites Examples
8. Entity referencing the OWASP Secure Headers Project (and sync the tab name)

# ❌ Cancelled

_Consider migrate the structure from **TAB** for **PAGE** to allow direct linking to content._

The tab direct link feature allow now to referencing a specific section.

_Consider refactor the icon used in favor of [feathericons](https://feathericons.com) ones combined with GitHub [emoji for Jekyll](https://github.com/jekyll/jemoji)._

The emoji provide a cool and pretty rendering that dynamically adapt to the rendering agent.

**Comment by righettod** [comment]
🚧 I started working on **Point B**...

**Comment by righettod** [comment]
@hblankenship What is the official way to customize the rendering at CSS level for a project website ?

Indeed, we need to tune the way in which table are rendering. Currently, we have this rendering:

![image](https://user-images.githubusercontent.com/1573775/224231582-b5fb560f-6559-4029-8786-a68c9a53ce92.png)

And using CSS we can tune it to adjust the column size:

![image](https://user-images.githubusercontent.com/1573775/224231674-633cbd4f-e8de-4ff3-a685-c91805312142.png)

Thanks a lot in advance 😃

**Comment by righettod** [comment]
Hi, very nice suggestions, I will apply it. Thanks again for your help.

**Comment by righettod** [comment]
Hi @riramar and @rfc-st 

I submitted the PR [133](https://github.com/OWASP/www-project-secure-headers/pull/133) to try to fix the issue and apply the suggestion from @rfc-st 

Hope it will be effective 🤞

**Comment by righettod** [comment]
Hi, new tentative with [PR 134](https://github.com/OWASP/www-project-secure-headers/pull/134) 😄

**Comment by righettod** [comment]
Hi, new tentative with [PR 135](https://github.com/OWASP/www-project-secure-headers/pull/135) 🤞

**Comment by righettod** [comment]
It's OK 😃

**Comment by hblankenship** [comment]
My first suggestion is to not use a table as it really isn't needed. You
could, for instance, because this is really just a list, display the
information as follows:



*Analysis Toolshsecscan [reference]*

A security scanner for HTTP response headers.

*humble [reference]*

A humble, and fast, security-oriented HTTP headers analyzer.



etc....
That said, the correct way to alter the CSS is to create your own local
versions of the CSS. You can do this in whatever manner the CSS supports.
For instance, see the
https://github.com/OWASP/www-projectchapter-example/tree/main/assets/css

Still, because tables are mobile ugly, I recommend using divs and
displaying as a better-looking list.

Regards,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects
*Contact Us
<https://owasporg.atlassian.net/servicedesk/customer/portal/7/create/72>*

*OWASP® **and **Open Web Application Security Project®  *
*Registered trademarks of the OWASP Foundation, Inc*

**Comment by righettod** [comment]
Thank you for your feedback @hblankenship

**Comment by righettod** [comment]
Point D implementation proposed in PR https://github.com/OWASP/www-project-secure-headers/pull/142

**Comment by righettod** [comment]
🚀 [PR 142](https://github.com/OWASP/www-project-secure-headers/pull/142) merged so this ticket is completed!
